package com.bpmn_exercise.employee_on_boarding;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmployeeDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "gender")
	private java.lang.String gender;

	public EmployeeDTO() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public EmployeeDTO(java.lang.String name, java.lang.String gender) {
		this.name = name;
		this.gender = gender;
	}

}